baseURL = "https://linesofcode.at"
languageCode = "en-us"
title = "Lines of Code"
theme="pixyll"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  #search_engine = true
  #google_analytics_id = ""
  twitter_username = "username"
  paginate = 5
